title: Pesquisas de Opinião sobre Diversidade
description: Rede Emílias de Podcasts

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-dinky


